"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret! Defina a
# variável de ambiente DJANGO_SECRET_KEY em produção -- o valor abaixo é só
# um fallback de desenvolvimento (por isso o prefixo "django-insecure-").
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-z^rr$agfkxt=k$!4*5)q&%u7-6p^y5fi*wn-085gu-&yqpaiyl',
)

# SECURITY WARNING: don't run with debug turned on in production! Defina
# DJANGO_DEBUG=False (via variável de ambiente) ao publicar fora da rede
# interna -- o padrão continua True para não quebrar o fluxo local de
# desenvolvimento (runserver) de quem não configurou a variável.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Defina DJANGO_ALLOWED_HOSTS como uma lista separada por vírgula
# (ex: "qcert.empresa.com,10.0.0.5") ao publicar com DEBUG=False.
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.app_Gestor',
    'core.app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Cache-busting (hash de conteúdo no nome do arquivo) só em produção -- exige
# rodar `collectstatic` antes de servir. Em dev (DEBUG=True) mantém o storage
# padrão pra não exigir esse passo extra em quem só roda `runserver`.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage'
            if DEBUG else
            'core.storage.NonStrictManifestStaticFilesStorage'
        ),
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

UPLOAD_DOCUMENTO_EXTENSOES_PERMITIDAS = ['.pdf', '.jpg', '.jpeg', '.png']
UPLOAD_DOCUMENTO_TAMANHO_MAXIMO_MB = 10

# Credencial do Mercado Pago via ambiente.
MERCADO_PAGO_ACCESS_TOKEN = os.getenv('MERCADO_PAGO_ACCESS_TOKEN', '')

# ID da planilha do Google Drive usada para sincronizar clientes/parceiros.
# Antes hardcoded em 5 lugares diferentes em app_Gestor/views.py; centralizado
# aqui e sobrescrevível via variável de ambiente.
GOOGLE_SHEET_ID = os.getenv('GOOGLE_SHEET_ID', '1L-MX27Y6iwCOyd0e4FqLxZJyRFCpHIP6arYYeFIHLME')

# TTL (segundos) do cache de leitura em memória do sheets_repository — evita
# que cada carregamento de tela de cada pessoa dispare uma chamada nova à API.
GOOGLE_SHEETS_CACHE_TTL_SECONDS = int(os.getenv('GOOGLE_SHEETS_CACHE_TTL_SECONDS', '20'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGS_DIR = BASE_DIR / 'logs'
os.makedirs(LOGS_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'default': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'default',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'qcert.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'default',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'WARNING',
    },
    'loggers': {
        'core': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
