"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret! Defina a
# variável de ambiente DJANGO_SECRET_KEY em produção -- o valor abaixo é só
# um fallback de desenvolvimento (por isso o prefixo "django-insecure-").
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-z^rr$agfkxt=k$!4*5)q&%u7-6p^y5fi*wn-085gu-&yqpaiyl',
)

# SECURITY WARNING: don't run with debug turned on in production! Defina
# DJANGO_DEBUG=False (via variável de ambiente) ao publicar fora da rede
# interna -- o padrão continua True para não quebrar o fluxo local de
# desenvolvimento (runserver) de quem não configurou a variável.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Defina DJANGO_ALLOWED_HOSTS como uma lista separada por vírgula
# (ex: "qcert.empresa.com,10.0.0.5") ao publicar com DEBUG=False.
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()]

# Defina DJANGO_CSRF_TRUSTED_ORIGINS como uma lista separada por vírgula de
# origens completas (ex: "https://qcert.empresa.com") se o app for acessado
# por HTTPS atrás de um domínio próprio.
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]

if not DEBUG:
    # Fora do modo de desenvolvimento, não deixa subir com a chave de
    # fallback nem sem ALLOWED_HOSTS -- as duas coisas que o README pede
    # pra configurar manualmente e são fáceis de esquecer.
    if SECRET_KEY.startswith('django-insecure-'):
        raise ImproperlyConfigured(
            'DJANGO_DEBUG=False exige DJANGO_SECRET_KEY definida (a chave de '
            'desenvolvimento não pode ser usada fora da rede interna).'
        )
    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured(
            'DJANGO_DEBUG=False exige DJANGO_ALLOWED_HOSTS definida.'
        )

    # Hardening de cookies/transporte -- só faz sentido fora do runserver
    # local em HTTP puro, por isso condicionado a DEBUG=False.
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 7  # 7 dias, sobe gradualmente depois de validar em produção
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.app_Gestor',
    'core.app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Exige login em toda view por padrão (Django 5.1+). Views que devem
    # ficar públicas usam o decorator @login_not_required.
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'

# Não há servidor com disco persistente -- login/senha não podem depender do
# SQLite local sobrevivendo entre execuções. Credenciais vivem na aba
# 'Usuarios' da planilha (mesma fonte de verdade de Clientes/Parceiros/
# Preços/Contatos); ver core/app_Gestor/auth_backends.py.
AUTHENTICATION_BACKENDS = [
    'core.app_Gestor.auth_backends.SheetsBackend',
    # Fallback só para permitir `createsuperuser` + /admin/ localmente em
    # máquina de desenvolvimento -- não afeta o fluxo normal de login, já
    # que usuários vindos do SheetsBackend sempre têm senha local inutilizável.
    'django.contrib.auth.backends.ModelBackend',
]

# Sessão inteira num cookie assinado no navegador em vez da tabela
# django_session -- sobrevive a reinícios/redeploys sem disco persistente,
# desde que DJANGO_SECRET_KEY fique estável entre execuções (já exigido
# acima quando DEBUG=False).
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Cache-busting (hash de conteúdo no nome do arquivo) só em produção -- exige
# rodar `collectstatic` antes de servir. Em dev (DEBUG=True) mantém o storage
# padrão pra não exigir esse passo extra em quem só roda `runserver`.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage'
            if DEBUG else
            'core.storage.NonStrictManifestStaticFilesStorage'
        ),
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

UPLOAD_DOCUMENTO_EXTENSOES_PERMITIDAS = ['.pdf', '.jpg', '.jpeg', '.png']
UPLOAD_DOCUMENTO_TAMANHO_MAXIMO_MB = 10

# Credencial do Mercado Pago via ambiente.
MERCADO_PAGO_ACCESS_TOKEN = os.getenv('MERCADO_PAGO_ACCESS_TOKEN', '')

# ID da planilha do Google Drive usada para sincronizar clientes/parceiros.
# Antes hardcoded em 5 lugares diferentes em app_Gestor/views.py; centralizado
# aqui e sobrescrevível via variável de ambiente.
GOOGLE_SHEET_ID = os.getenv('GOOGLE_SHEET_ID', '1L-MX27Y6iwCOyd0e4FqLxZJyRFCpHIP6arYYeFIHLME')

# TTL (segundos) do cache de leitura em memória do sheets_repository — evita
# que cada carregamento de tela de cada pessoa dispare uma chamada nova à API.
GOOGLE_SHEETS_CACHE_TTL_SECONDS = int(os.getenv('GOOGLE_SHEETS_CACHE_TTL_SECONDS', '20'))

# Pasta raiz no Google Drive onde as pastas por cliente são criadas (uma
# subpasta "<id> - <nome>" por cliente, na primeira vez que um documento é
# enviado). Precisa estar dentro de um Shared Drive (Workspace) compartilhado
# com o email do service account (permissão Editor) -- uma pasta comum
# compartilhada cria subpasta mas falha no upload (service account não tem
# quota própria fora de Shared Drive). Ver drive_repository.py.
GOOGLE_DRIVE_ROOT_FOLDER_ID = os.getenv('GOOGLE_DRIVE_ROOT_FOLDER_ID', '')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGS_DIR = BASE_DIR / 'logs'
os.makedirs(LOGS_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'default': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'default',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'qcert.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'default',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'WARNING',
    },
    'loggers': {
        'core': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# Monitoramento de erros (opcional) -- só ativa se SENTRY_DSN estiver
# definida; sem ela, é um no-op completo (dev local não precisa de conta).
SENTRY_DSN = os.getenv('SENTRY_DSN', '')
if SENTRY_DSN:
    import sentry_sdk

    sentry_sdk.init(dsn=SENTRY_DSN, send_default_pii=False, traces_sample_rate=0.0)
